# Goal use a running job to generate artifacts as a log file and check if the artifacts are generated successfully or not.
name: check_artifacts
on:
  push:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: run nginx server 
        run: |  
            echo "Starting nginx server..."
            sudo apt-get update
            sudo apt-get install -y nginx
            sudo systemctl start nginx
            echo "Nginx server started."

      - name: Generate Access Logs
        run: |
            echo "Generating access logs..."
            curl -I http://localhost
            echo "Access logs generated."
       
      - name: Show NGINX Logs
        if: always()
        run: |
            echo "--- Access Logs ---"
            sudo cat /var/log/nginx/access.log  

      - name: Upload Artifact for Access Logs
        uses: actions/upload-artifact@v4
        with:
            name: nginx-access-logs
            path: /var/log/nginx/access.log
            retention-days: 5
  download:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - name: Download Artifact for Access Logs
        uses: actions/download-artifact@v4
        with:
            name: nginx-access-logs
