# Goal use a running job to generate artifacts as a log file and check if the artifacts are generated successfully or not.
name: check_artifacts
on:
  push:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: run nginx server 
        run: |  
            echo "Starting nginx server..."
            sudo apt-get update
            sudo apt-get install -y nginx
            sudo systemctl start nginx
            echo "Nginx server started."
       
      - name: Show NGINX Logs
        if: always()
        run: |
            echo "--- Access Logs ---"
            sudo cat /var/log/nginx/access.log
            echo "--- Error Logs ---"
            sudo cat /var/log/nginx/error.log