name: GitHub-Hosted Runners Info

on:
  workflow_dispatch:

jobs:
  ubuntu-job:
    name: Ubuntu Runner Info
    runs-on: ubuntu-latest
    steps:
      - name: Print the pre installed versions
        run: |

          docker --version
          python3 --version
          node --version
          git --version
      
      

