name: GitHub-Hosted Runners Info

on:
  workflow_dispatch:

jobs:
  ubuntu-job:
    name: Ubuntu Runner Info
    runs-on: ubuntu-latest
    steps:
      - name: Print Runner Information
        run: |
          echo "OS Name: Linux (Ubuntu)"
          echo "Hostname: $(hostname)"
          echo "Current User: $(whoami)"

  windows-job:
    name: Windows Runner Info
    runs-on: windows-latest
    steps:
      - name: Print Runner Information
        shell: cmd
        run: |
          echo OS Name: Windows
          echo Hostname: %COMPUTERNAME%
          echo Current User: %USERNAME%

  macos-job:
    name: macOS Runner Info
    runs-on: macos-latest
    steps:
      - name: Print Runner Information
        run: |
          echo "OS Name: macOS"
          echo "Hostname: $(hostname)"
          echo "Current User: $(whoami)"
