name: Environmaent Variable
on:
  workflow_dispatch:

# setting a workflow-level environment variable
env:
  APP_NAME: myapp

jobs:
  env-var-job:
    runs-on: ubuntu-latest

    # setting a job-level environment variable
    env:
      ENVIRONMENT: staging
    steps:
      - name: Print Environment Variables  
        run: |
          echo "Application Name: ${{ env.APP_NAME }}"
          echo "Environment: ${{ env.ENVIRONMENT }}"
          echo "Step Environment Variable: ${{ env.VERSION }}"

          echo "---"
          
          echo "=== GitHub Context Variables ==="
          echo "Commit SHA: ${{ github.sha }}"
          echo "Actor (Triggered by): ${{ github.actor }}"
        
        # setting a step-level environment variable
        env:
          VERSION: 1.0.0