name: multi-job
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the code
        run: echo "Building the code"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Run test cases
        run: echo "Running test cases"
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the code
        run: echo "Deploying the code"