name: hello-world
on:
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Print Hello World message
        run: |
          echo "Hello, World!"