name: system_check thrugh shell script
on:
  push:
jobs:
  system_check:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repository code
        uses: actions/checkout@v6
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
     
      - name: adding cache for the script
        uses: actions/cache@v4 
        with:
          path: ./system_info.sh
          key: ${{ runner.os }}-script-run-${{ github.sha }}
         # Falls back to the most recent cache available if an exact match isn't found
          restore-keys: |
            ${{ runner.os }}-script-run-
      
      - name: Run System Check Script  
        run: |
          chmod +x ./system_info.sh
          ./system_info.sh 
      
      - name: Fail the job if the script fails
        if: failure()
        run: |
          echo "System check script failed. Please check the logs for details."
          exit 1                  