name: Path & Branch Filters

on:
  push:
    paths:
      - 'src/**'
      - 'app/**'
    branches:
      - main
      - 'release/*'

jobs: 
  printing-the-status:
    runs-on: ubuntu-latest # Fixed the colon to a hyphen
    steps:
      - name: This step prints a hello msg
        run: |
          echo "hellow dosto"
