name: Path & Branch Filters

on:
  push:
    paths:
      - 'src/**'
      - 'app/**'

    branches:
      - main
      - release/*
jobs: 
    printing-the-status:
     runs-on: ubuntu:latest
     steps:
      - name: this step print a hellow msg
        run: |
            echo "hellow dosto"
  
